### ISSUE TITLE
./build_ocarina.sh: line 180: git: command not found

### ISSUE THREAD

**Issue by dvogiatzakis** [OpenAADL/ocarina-build#34]
I get this error message as I try to install Ocarina into WIndows 10 through cygwin64

[2018-01-13-01:25] Checkout the Ocarina sources
./build_ocarina.sh: line 180: git: command not found

Please, can you help?

**Comment by yoogx** [comment]
I think the message is self-explanatory: we use git tool to fetch ocarina source code. You need to install it and make sure it is in your path. Since you use cygwin, I assume you can install the git tool from their package manager

**Comment by dvogiatzakis** [comment]
Thank you very much! You are right, it is self-explanatory, I 'm not very familiar with Git.

**Comment by youjiandada** [comment]
> Thank you very much! You are right, it is self-explanatory, I 'm not very familiar with Git.

Hello,-dvogiatzakis-.I have the same problem as you. Now I have improved according to the above, but there are still problems. I want to know whether you have solved the problem after installing “Git Tools”?

**Comment by youjiandada** [comment]
![image](https://user-images.githubusercontent.com/45002190/90127170-55f2d800-dd97-11ea-9bca-668f0f7f60d8.png)
The above is the problem I encountered when I installed Ocarina. Since the online installation can not find the source normally, can I solve it by installing the local package, or can I modify the configuration ". Sh" of "Ocarina build master" to install in a mirror mode?

**Comment by yoogx** [comment]
I do not know what you mean by local package. If you download the archive from Github; and place it in the same place as the git repository, i.e. ocarina/ relative to build-ocarina, then you can simply run build_ocarina with the --configure --build --install flags. See doc for more details/corrections
