### ISSUE TITLE
Build on Windows / Which GNAT version ?

### ISSUE THREAD

**Issue by dvogiatzakis** [OpenAADL/ocarina-build#35]
I tried a new installation using git clone first. The scripts keep showing this message. I tried this solution {https://learningintheopen.org/2013/03/07/microsoft-windows-cygwin-error-r-command-not-found/} for the initial script: "./build-ocarina.sh" and it worked but I can't change the next one "./get_runtimes.sh" if I'm running the initial script (cause it fetches it again). Should I run all the scripts manually after changing the format? 
Oh, I'm still trying the build in Windows/cygwin64.
Thank you

**Comment by dvogiatzakis** [comment]
Well, I'm sorry again... When you say "local" folder of installation you mean inside cygwin. Now it's working but I still have a problem with the Ada cross compiler. Do I have to build it in Cygwin? Because I have the gcc toolchain in my path. Any help would be much appreciated!!

**Comment by yoogx** [comment]
I just tested on my Windows VM, running "./build-ocarina.sh --scenario=fresh-install" from Cygwin terminal properly downloads all source. Can you please precise the steps you executed ?

**Comment by dvogiatzakis** [comment]
Thank you very much for your reply.
I installed cygwin and enough devel packages through the installer and then I execute the git clone command, then the script: ./build_ocarina.sh --scenario=fresh-install. Everything passes but the configuration fails due to Ada cross compiler miss. So, do I have to build it in cygwin? I'm pretty sure I have the toolchain needed.

**Comment by yoogx** [comment]
Cygwin used to ship the mingw64-x86_64-gcc-ada package. This seems no longer the case. Let me dig into this issue.

**Comment by dvogiatzakis** [comment]
If I understand correctly, this package is obsolete and is now part of the
x86_64-w64-mingw32-gcc-core.

**Comment by jstegen** [comment]
Any update on this? I have the same problem
Thanks

**Comment by yoogx** [comment]
Hopefully, it was enough to wait for a batch of updates

You may want to install msys2, it proposes a recent version of GCC with Ada support, 7.3.0.
I could either 
- compile Ocarina from cygwin shell, pointing path to msys2 install directory
- compile Ocarina from msys2 shell, after installation of mingw-w64-x86_64-gcc-ada + make, git, autoconf, automake and python

I recommend the later solution. Closing this issue

**Comment by bulletshot60** [comment]
Since I also had this issue, I'll share that it is still possible to build using Cygwin on windows using the [Cygwin Time Machine](http://www.crouchingtigerhiddenfruitbat.org/Cygwin/timemachine.html).  The version circa [2017/07/31](http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2017/07/31/131629) worked for me.  Note you have to run the cygwin installer with the `-X` option to use the time machine.

For a fresh install, you need the `automake`, `autoconf`, `mingw64-x86_x64-gcc-ada`, `mingw64-x86_x64-gcc-g++`, `gcc-ada`, `python2` and `make` (the GNU version) packages.  You'll also need to edit your `.bash_profile` to include:

```bash
export SHELLOPTS
set -o igncr
```

Or if you're lazy and don't feel like going that route, I published the build I just did [here](https://s3.amazonaws.com/ocarina-windows-builds/ocarina-20180307.zip).

**Comment by yoogx** [comment]
Thanks for the report. Good to know you're still using Ocarina.
